services:
  app:
    build:
      context: ./App
      dockerfile: dockerfile
    image: ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:app-${GITHUB_SHA}
    container_name: appp
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - monitoring

  prometheus:
    build:
      context: ./prometheus
    image: ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:prometheus-${GITHUB_SHA}
    container_name: prometheusu
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    build:
      context: ./grafana
    image: ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:grafana-${GITHUB_SHA}
    container_name: grafanaa
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge