name: Deploy Multi-Service App to Cloud Run

on:
  push:
    branches: [ "monitoring" ]

env:
  DOCKER_HUB_USERNAME: aimanahmad0004
  REPOSITORY_NAME: monitor
  PROJECT_ID: chillguys
  REGION: asia-southeast1
  NODE_ENV: production

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker Compose (if needed, but we're using build-push-action)
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version || echo "Docker Compose installation failed"

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker images for each service in docker-compose.yml
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .  # Set context to the root directory (or change if Dockerfile is in a subdirectory)
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          file: ./Dockerfile  # Specify path to Dockerfile if it's in a subfolder like ./app/Dockerfile

      # Google Auth for GCP
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Deploy each service to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          # Get list of services from docker-compose.yml
          services=$(docker-compose -f docker-compose.yml config --services)
          
          for service in $services; do
            # Build docker image name
            docker_image="${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}-${service}:${{ github.sha }}"

            # Deploy to Cloud Run
            gcloud run deploy $service \
              --image $docker_image \
              --region ${{ env.REGION }} \
              --allow-unauthenticated \
              --platform managed \
              --project ${{ env.PROJECT_ID }} \
              --set-env-vars NODE_ENV=${{ env.NODE_ENV }}
          done
