name: Deploy Multi-Service App to Cloud Run

on:
  push:
    branches: [ "monitoring" ]

env:
  DOCKER_HUB_USERNAME: aimanahmad0004
  REPOSITORY_NAME: monitor
  PROJECT_ID: chillguys
  REGION: asia-southeast1
  NODE_ENV: production

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker --version
          docker-compose --version

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker images using docker-compose
      - name: Build and push Docker images
        env:
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_HUB_USERNAME: ${{ env.DOCKER_HUB_USERNAME }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
        run: |
          echo "Current images in Docker:"
          docker images
          
          echo "Building images..."
          docker-compose -f docker-compose.yml build --no-cache
          
          echo "Images after build:"
          docker images
          
          echo "Tagging images..."
          docker tag ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}-app:${GITHUB_SHA} ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:app-${GITHUB_SHA}
          docker tag ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}-prometheus:${GITHUB_SHA} ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:prometheus-${GITHUB_SHA}
          docker tag ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}-grafana:${GITHUB_SHA} ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:grafana-${GITHUB_SHA}
          
          echo "Pushing images to Docker Hub..."
          docker push ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:app-${GITHUB_SHA}
          docker push ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:prometheus-${GITHUB_SHA}
          docker push ${DOCKER_HUB_USERNAME}/${REPOSITORY_NAME}:grafana-${GITHUB_SHA}
          
          echo "Final images in Docker:"
          docker images

      # Google Auth for GCP
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Deploy to Cloud Run for each service
      - name: Deploy to Cloud Run
        run: |
          # Deploy app service
          echo "Deploying app service..."
          gcloud run deploy app \
            --image docker.io/${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:app-${{ github.sha }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars NODE_ENV=${{ env.NODE_ENV }}

          # Deploy prometheus service
          echo "Deploying prometheus service..."
          gcloud run deploy prometheus \
            --image docker.io/${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:prometheus-${{ github.sha }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars NODE_ENV=${{ env.NODE_ENV }}

          # Deploy grafana service
          echo "Deploying grafana service..."
          gcloud run deploy grafana \
            --image docker.io/${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:grafana-${{ github.sha }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars NODE_ENV=${{ env.NODE_ENV }}