name: Deploy to Cloud Run from Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: softaki23
  REPOSITORY_NAME: test-repo
  PROJECT_ID: chillguys
  REGION: asia-southeast1
  SERVICE_NAME: calculator-app
  PORT: 80
  NODE_ENV: production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}

      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          # Ensure the container is running in the foreground for debugging
          docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          # Check if the container is running
          docker ps
#test
