name: Deploy Website

on:
  push:
    branches:
      - dev/davey  # Trigger deployment on pushes to the branch

env:
  USERNAME: root
  HOST : '134.209.112.240'
  PORT : 22
  PASSWORD : T3stinGA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH for communication with the Droplet
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          port: ${{ env.PORT }}
          command_timeout: 30m
          script: | 
            echo "Connecting to ${{ env.HOST }}..."
            echo "${{ env.PASSWORD }}"

      # Step 3: Pull the latest changes from the Git repository on the Droplet
      - name: Pull latest code and rebuild Docker container
        run: |
          ssh -o StrictHostKeyChecking=no root@134.209.112.240 << 'EOF'
            cd docker-app/Yayasan-Chill-Guy
            git pull origin dev/davey  # Pull the latest changes
            docker build -t dvy4/basiccalculator2 .  # Rebuild Docker image
            docker stop $(docker ps -q --filter ancestor=dvy4/basiccalculator2)  # Stop the old container
            docker rm $(docker ps -a -q --filter ancestor=dvy4/basiccalculator2)  # Remove old container
            docker run -d -p 80:80 dvy4/basiccalculator2  # Start the new container
          EOF
